services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xiv-voices-admin
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://xivvoices:xivvoices_password@postgres:5432/xivvoices_db?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      # The following environment variables should be set in a .env file or through Docker secrets in production
      # - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      # - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      # - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    # Add a healthcheck to ensure the application is running properly
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:latest
    container_name: xiv-voices-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: xivvoices
      POSTGRES_PASSWORD: xivvoices_password
      POSTGRES_DB: xivvoices_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xivvoices"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: